package types

import (
	"encoding/hex"
	"errors"
	"fmt"

	sdk "github.com/cosmos/cosmos-sdk/types"
)

const (
	IdentityWalletStateVerifiedCurrentV2	IdentityWalletResolutionStateV2	= "verified_current"
	IdentityWalletStateVerifiedStaleV2	IdentityWalletResolutionStateV2	= "verified_stale"
	IdentityWalletStateUnverifiedClaimV2	IdentityWalletResolutionStateV2	= "unverified_claim"
	IdentityWalletStateProofFailedV2	IdentityWalletResolutionStateV2	= "proof_failed"
	IdentityWalletStateExpiredV2		IdentityWalletResolutionStateV2	= "expired"
	IdentityWalletStateOwnershipMismatchV2	IdentityWalletResolutionStateV2	= "ownership_mismatch"
	IdentityWalletStateResolverMissingV2	IdentityWalletResolutionStateV2	= "resolver_missing"

	IdentityWalletFallbackFreshProofOtherNodeV2	IdentityWalletFallbackActionV2	= "request_fresh_proof_from_another_full_node"
	IdentityWalletFallbackNewerTrustedHeightV2	IdentityWalletFallbackActionV2	= "request_proof_at_newer_trusted_height"
	IdentityWalletFallbackUseVerifiedCacheV2	IdentityWalletFallbackActionV2	= "use_previously_verified_cache_within_ttl"
	IdentityWalletFallbackExplicitAddressV2		IdentityWalletFallbackActionV2	= "require_explicit_address_entry"
	IdentityWalletFallbackDisableGeneratedUIV2	IdentityWalletFallbackActionV2	= "disable_auto_generated_contract_or_service_ui"

	IdentityWalletFailureKindStaleProofV2		IdentityWalletProofFailureKindV2	= "stale"
	IdentityWalletFailureKindMissingProofV2		IdentityWalletProofFailureKindV2	= "missing"
	IdentityWalletFailureKindInvalidProofV2		IdentityWalletProofFailureKindV2	= "invalid"
	IdentityWalletFailureKindUntrustedProofV2	IdentityWalletProofFailureKindV2	= "untrusted"

	IdentityWalletOperationSendByNameV2	IdentityWalletOperationV2	= "send_by_name"
	IdentityWalletOperationInvokeByNameV2	IdentityWalletOperationV2	= "invoke_by_name"
	IdentityWalletOperationReverseLookupV2	IdentityWalletOperationV2	= "reverse_lookup"
	IdentityWalletOperationServiceLookupV2	IdentityWalletOperationV2	= "service_endpoint_discovery"
)

type IdentityWalletResolutionStateV2 string

type IdentityWalletFallbackActionV2 string

type IdentityWalletProofFailureKindV2 string

type IdentityWalletOperationV2 string

type IdentityWalletFallbackPolicyV2 struct {
	CurrentHeight		uint64
	FreshnessThreshold	uint64
	AllowVerifiedCache	bool
	UserAllowsCache		bool
	DirectAddressConfirmed	bool
	InterfaceProofRequired	bool
	InterfaceProofFailed	bool
}

type IdentityWalletFallbackDecisionV2 struct {
	FailureKind			IdentityWalletProofFailureKindV2
	FailureCode			IdentityLightClientFailureCodeV2
	OrderedActions			[]IdentityWalletFallbackActionV2
	UseVerifiedCache		bool
	RequiresExplicitAddressEntry	bool
	DisableAutoGeneratedUI		bool
	NoSilentDowngrade		bool
	DirectAddressFallbackAllowed	bool
	CacheRejectedReason		string
}

type IdentityWalletProofCacheMetadataV2 struct {
	FormattedKey		string
	ProofHeight		uint64
	RecordVersion		uint64
	ResolverTTL		uint64
	DomainExpiryHeight	uint64
	FreshUntilHeight	uint64
	TrustedHeaderChainID	string
	TrustedHeaderHeight	uint64
	TrustedHeaderAppHash	string
	Verified		bool
	LightClient		bool
	StaleWarningThreshold	uint64
	AdvancedDetails		string
}

type IdentityWalletUXPolicyV2 struct {
	Operation		IdentityWalletOperationV2
	CurrentHeight		uint64
	FreshnessThreshold	uint64
	AllowVerifiedCache	bool
	UserAllowsCache		bool
	DirectAddressConfirmed	bool
	ContractTargetVerified	bool
	InterfaceProofRequired	bool
	InterfaceProofVerified	bool
	ReverseLookup		bool
	ServiceEndpoint		bool
}

type IdentityWalletResolutionUXRequestV2 struct {
	Name			string
	Target			*IdentityLightClientVerifiedTargetV2
	ProofError		error
	CacheMetadata		*IdentityVerifiedCacheMetadataV2
	Policy			IdentityWalletUXPolicyV2
	DirectAddress		sdk.AccAddress
	OverrideReason		string
	OverrideCreatedHeight	uint64
}

type IdentityWalletResolutionUXV2 struct {
	State				IdentityWalletResolutionStateV2
	Fallback			IdentityWalletFallbackDecisionV2
	CacheMetadata			*IdentityWalletProofCacheMetadataV2
	CanSendByName			bool
	CanInvokeByName			bool
	ReverseCanonical		bool
	ServiceAdvancedDetails		string
	AutoGeneratedUIDisabled		bool
	StaleProofWarning		bool
	ExplicitOverrideRequired	bool
	OverrideAudit			*IdentityWalletOverrideAuditTrailV2
}

type IdentityWalletOverrideAuditTrailV2 struct {
	OverrideID		string
	Name			string
	Operation		IdentityWalletOperationV2
	OriginalState		IdentityWalletResolutionStateV2
	FailureCode		IdentityLightClientFailureCodeV2
	DirectAddressHex	string
	Reason			string
	UserConfirmed		bool
	CreatedAtHeight		uint64
	CacheProofHeight	uint64
	AuditHash		string
}

func EvaluateIdentityWalletFallbackStrategyV2(proofErr error, cache *IdentityVerifiedCacheMetadataV2, policy IdentityWalletFallbackPolicyV2) IdentityWalletFallbackDecisionV2 {
	code, found := IdentityLightClientFailureCodeFromErrorV2(proofErr)
	if !found {
		code = IdentityLightClientErrProofInvalid
	}
	decision := IdentityWalletFallbackDecisionV2{
		FailureKind:			classifyWalletProofFailureV2(code),
		FailureCode:			code,
		OrderedActions:			[]IdentityWalletFallbackActionV2{IdentityWalletFallbackFreshProofOtherNodeV2, IdentityWalletFallbackNewerTrustedHeightV2},
		NoSilentDowngrade:		true,
		DirectAddressFallbackAllowed:	policy.DirectAddressConfirmed,
	}
	if cache != nil && policy.AllowVerifiedCache && policy.UserAllowsCache {
		current := policy.CurrentHeight
		if current == 0 {
			current = cache.ProofHeight
		}
		if err := ValidateIdentityVerifiedCacheFreshnessV2(*cache, current, policy.FreshnessThreshold, false); err == nil {
			decision.UseVerifiedCache = true
			decision.OrderedActions = append(decision.OrderedActions, IdentityWalletFallbackUseVerifiedCacheV2)
		} else {
			decision.CacheRejectedReason = err.Error()
		}
	} else if cache != nil {
		decision.CacheRejectedReason = "verified cache fallback is disabled by policy"
	}
	decision.OrderedActions = append(decision.OrderedActions, IdentityWalletFallbackExplicitAddressV2)
	decision.RequiresExplicitAddressEntry = true
	if policy.InterfaceProofFailed || (policy.InterfaceProofRequired && code == IdentityLightClientErrProofInvalid) {
		decision.OrderedActions = append(decision.OrderedActions, IdentityWalletFallbackDisableGeneratedUIV2)
		decision.DisableAutoGeneratedUI = true
	}
	return decision
}

func BuildIdentityWalletResolutionUXV2(request IdentityWalletResolutionUXRequestV2) (IdentityWalletResolutionUXV2, error) {
	state := IdentityWalletStateUnverifiedClaimV2
	var fallback IdentityWalletFallbackDecisionV2
	if request.ProofError != nil {
		state = walletStateFromProofErrorV2(request.ProofError)
		fallback = EvaluateIdentityWalletFallbackStrategyV2(request.ProofError, request.CacheMetadata, IdentityWalletFallbackPolicyV2{
			CurrentHeight:		request.Policy.CurrentHeight,
			FreshnessThreshold:	request.Policy.FreshnessThreshold,
			AllowVerifiedCache:	request.Policy.AllowVerifiedCache,
			UserAllowsCache:	request.Policy.UserAllowsCache,
			DirectAddressConfirmed:	request.Policy.DirectAddressConfirmed,
			InterfaceProofRequired:	request.Policy.InterfaceProofRequired,
			InterfaceProofFailed:	!request.Policy.InterfaceProofVerified && request.Policy.InterfaceProofRequired,
		})
	} else if request.Target != nil {
		state = walletStateFromVerifiedTargetV2(*request.Target, request.Policy.CurrentHeight, request.Policy.FreshnessThreshold)
	}
	out := IdentityWalletResolutionUXV2{
		State:				state,
		Fallback:			fallback,
		ExplicitOverrideRequired:	state != IdentityWalletStateVerifiedCurrentV2,
		AutoGeneratedUIDisabled:	fallback.DisableAutoGeneratedUI,
	}
	if request.CacheMetadata != nil {
		meta, err := BuildIdentityWalletProofCacheMetadataV2(*request.CacheMetadata, request.Policy.FreshnessThreshold)
		if err != nil && request.ProofError == nil {
			return IdentityWalletResolutionUXV2{}, err
		}
		if err == nil {
			out.CacheMetadata = &meta
			out.ServiceAdvancedDetails = meta.AdvancedDetails
		}
	}
	out.StaleProofWarning = state == IdentityWalletStateVerifiedStaleV2
	out.CanSendByName = state == IdentityWalletStateVerifiedCurrentV2 && effectiveWalletOperationV2(request.Policy.Operation) == IdentityWalletOperationSendByNameV2
	out.CanInvokeByName = state == IdentityWalletStateVerifiedCurrentV2 &&
		effectiveWalletOperationV2(request.Policy.Operation) == IdentityWalletOperationInvokeByNameV2 &&
		request.Policy.ContractTargetVerified &&
		(!request.Policy.InterfaceProofRequired || request.Policy.InterfaceProofVerified)
	out.ReverseCanonical = state == IdentityWalletStateVerifiedCurrentV2 && (request.Policy.ReverseLookup || effectiveWalletOperationV2(request.Policy.Operation) == IdentityWalletOperationReverseLookupV2)
	if request.Policy.ServiceEndpoint {
		out.ServiceAdvancedDetails = walletServiceAdvancedDetailsV2(out.CacheMetadata)
	}
	if request.Policy.DirectAddressConfirmed && state != IdentityWalletStateVerifiedCurrentV2 {
		audit, err := NewIdentityWalletOverrideAuditTrailV2(request, state, fallback.FailureCode)
		if err != nil {
			return IdentityWalletResolutionUXV2{}, err
		}
		out.OverrideAudit = &audit
		out.ExplicitOverrideRequired = false
		if effectiveWalletOperationV2(request.Policy.Operation) == IdentityWalletOperationSendByNameV2 {
			out.CanSendByName = true
		}
	}
	if request.Policy.InterfaceProofRequired && !request.Policy.InterfaceProofVerified {
		out.AutoGeneratedUIDisabled = true
		out.CanInvokeByName = false
	}
	return out, nil
}

func BuildIdentityWalletProofCacheMetadataV2(metadata IdentityVerifiedCacheMetadataV2, staleWarningThreshold uint64) (IdentityWalletProofCacheMetadataV2, error) {
	if err := ValidateIdentityVerifiedCacheMetadataV2(metadata); err != nil {
		return IdentityWalletProofCacheMetadataV2{}, err
	}
	formatted, err := FormatIdentityResolutionCacheKeyV2(metadata.Key)
	if err != nil {
		return IdentityWalletProofCacheMetadataV2{}, err
	}
	out := IdentityWalletProofCacheMetadataV2{
		FormattedKey:		formatted,
		ProofHeight:		metadata.ProofHeight,
		RecordVersion:		metadata.Key.RecordVersion,
		ResolverTTL:		metadata.ResolverTTL,
		DomainExpiryHeight:	metadata.DomainExpiryHeight,
		FreshUntilHeight:	metadata.FreshUntilHeight,
		TrustedHeaderChainID:	metadata.TrustedHeaderChainID,
		TrustedHeaderHeight:	metadata.TrustedHeaderHeight,
		TrustedHeaderAppHash:	metadata.TrustedHeaderAppHash,
		Verified:		metadata.Verified,
		LightClient:		metadata.LightClient,
		StaleWarningThreshold:	staleWarningThreshold,
	}
	out.AdvancedDetails = fmt.Sprintf("proof_height=%d ttl=%d fresh_until=%d record_version=%d", out.ProofHeight, out.ResolverTTL, out.FreshUntilHeight, out.RecordVersion)
	return out, nil
}

func NewIdentityWalletOverrideAuditTrailV2(request IdentityWalletResolutionUXRequestV2, state IdentityWalletResolutionStateV2, failureCode IdentityLightClientFailureCodeV2) (IdentityWalletOverrideAuditTrailV2, error) {
	if !request.Policy.DirectAddressConfirmed {
		return IdentityWalletOverrideAuditTrailV2{}, errors.New("identity wallet override requires explicit user confirmation")
	}
	if err := validateSpecAddress("identity wallet override direct address", request.DirectAddress); err != nil {
		return IdentityWalletOverrideAuditTrailV2{}, err
	}
	if request.OverrideReason == "" {
		return IdentityWalletOverrideAuditTrailV2{}, errors.New("identity wallet override reason is required")
	}
	if request.OverrideCreatedHeight == 0 {
		return IdentityWalletOverrideAuditTrailV2{}, errors.New("identity wallet override created height is required")
	}
	name := request.Name
	if request.Target != nil && request.Target.Name != "" {
		name = request.Target.Name
	}
	normalized, err := NormalizeAETDomain(name)
	if err != nil {
		return IdentityWalletOverrideAuditTrailV2{}, err
	}
	cacheProofHeight := uint64(0)
	if request.CacheMetadata != nil {
		cacheProofHeight = request.CacheMetadata.ProofHeight
	}
	out := IdentityWalletOverrideAuditTrailV2{
		Name:			normalized,
		Operation:		effectiveWalletOperationV2(request.Policy.Operation),
		OriginalState:		state,
		FailureCode:		failureCode,
		DirectAddressHex:	hex.EncodeToString(request.DirectAddress),
		Reason:			request.OverrideReason,
		UserConfirmed:		true,
		CreatedAtHeight:	request.OverrideCreatedHeight,
		CacheProofHeight:	cacheProofHeight,
	}
	out.AuditHash = identityHash("identity-wallet-override-v2", out.Name, string(out.Operation), string(out.OriginalState), string(out.FailureCode), out.DirectAddressHex, out.Reason, fmt.Sprintf("%020d", out.CreatedAtHeight), fmt.Sprintf("%020d", out.CacheProofHeight))
	out.OverrideID = out.AuditHash
	return out, nil
}

func walletStateFromVerifiedTargetV2(target IdentityLightClientVerifiedTargetV2, currentHeight uint64, threshold uint64) IdentityWalletResolutionStateV2 {
	if target.ProofHeight == 0 || target.RecordVersion == 0 {
		return IdentityWalletStateUnverifiedClaimV2
	}
	if currentHeight == 0 {
		currentHeight = target.ProofHeight
	}
	if target.FreshUntilHeight != 0 && currentHeight > target.FreshUntilHeight {
		return IdentityWalletStateVerifiedStaleV2
	}
	if threshold == 0 {
		threshold = DefaultIdentityFreshnessWindowV2
	}
	if currentHeight > target.ProofHeight+threshold {
		return IdentityWalletStateVerifiedStaleV2
	}
	return IdentityWalletStateVerifiedCurrentV2
}

func walletStateFromProofErrorV2(err error) IdentityWalletResolutionStateV2 {
	code, found := IdentityLightClientFailureCodeFromErrorV2(err)
	if !found {
		return IdentityWalletStateProofFailedV2
	}
	switch code {
	case IdentityLightClientErrDomainExpired:
		return IdentityWalletStateExpiredV2
	case IdentityLightClientErrNFTBindingMismatch:
		return IdentityWalletStateOwnershipMismatchV2
	case IdentityLightClientErrResolverNotFound:
		return IdentityWalletStateResolverMissingV2
	default:
		return IdentityWalletStateProofFailedV2
	}
}

func classifyWalletProofFailureV2(code IdentityLightClientFailureCodeV2) IdentityWalletProofFailureKindV2 {
	switch code {
	case IdentityLightClientErrRecordStale, IdentityLightClientErrDomainExpired:
		return IdentityWalletFailureKindStaleProofV2
	case IdentityLightClientErrDomainNotFound, IdentityLightClientErrResolverNotFound, IdentityLightClientErrTargetNotFound:
		return IdentityWalletFailureKindMissingProofV2
	case IdentityLightClientErrProofHeightUntrusted:
		return IdentityWalletFailureKindUntrustedProofV2
	default:
		return IdentityWalletFailureKindInvalidProofV2
	}
}

func effectiveWalletOperationV2(operation IdentityWalletOperationV2) IdentityWalletOperationV2 {
	if operation == "" {
		return IdentityWalletOperationSendByNameV2
	}
	return operation
}

func walletServiceAdvancedDetailsV2(metadata *IdentityWalletProofCacheMetadataV2) string {
	if metadata == nil {
		return "proof_height=0 ttl=0"
	}
	return metadata.AdvancedDetails
}
