param(
  [string]$Doc = "docs\architecture\aetra-staking-policy-spec.md",
  [string]$Policy = "app\params\aetra_staking_policy_spec.go",
  [string]$Tests = "app\params\aetra_staking_policy_spec_test.go"
)

$ErrorActionPreference = "Stop"

$RepoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\.."))

function Resolve-RepoPath {
  param([string]$Path)
  if ([System.IO.Path]::IsPathRooted($Path)) { return $Path }
  return Join-Path $RepoRoot $Path
}

function Assert-Contains {
  param([string]$Text, [string]$Pattern, [string]$Message)
  if ($Text -notmatch $Pattern) { throw $Message }
}

$docText = Get-Content -Raw -LiteralPath (Resolve-RepoPath $Doc)
$policyText = Get-Content -Raw -LiteralPath (Resolve-RepoPath $Policy)
$testText = Get-Content -Raw -LiteralPath (Resolve-RepoPath $Tests)

foreach ($term in @(
    'x/aetra-staking-policy Module Specification',
    'Purpose: control effective voting power, delegation overflow, commission policy, and anti-concentration incentives.',
    'This module is the central anti-centralization module of Aetra.',
    'calculate raw validator stake',
    'calculate effective validator stake',
    'calculate overflow stake',
    'enforce or expose effective voting power cap',
    'calculate reward multiplier for overflow stake',
    'expose delegation concentration warnings',
    'enforce commission floor',
    'enforce max commission',
    'enforce max commission change rate',
    'expose top-N concentration metrics',
    'validate governance param changes',
    'emit events for cap/overflow/commission policy changes',
    'remain deterministic and export/import safe',
    'staking policy = stake math + cap enforcement/exposure + overflow accounting + commission policy + concentration metrics + governance params + events + export/import safety + tests + docs',
    'The implementation gate is `app/params/aetra_staking_policy_spec.go`',
    '`AetraStakingPolicyModuleName` must be `x/aetra-staking-policy`',
    'wrong or missing module identity is rejected',
    '22.2 State',
    'Params:',
    'MaxValidatorsSoftTarget',
    'ValidatorPowerCapBps',
    'ValidatorPowerCapSchedule',
    'OverflowRewardMultiplierBps',
    'CommissionFloorBps',
    'CommissionMaxBps',
    'CommissionMaxDailyChangeBps',
    'Top10TargetBps',
    'Top20TargetBps',
    'Top33TargetBps',
    'MinSelfBond',
    'MinValidatorBond',
    'WarningThresholdBps',
    'ValidatorPolicy:',
    'OperatorAddress',
    'RawBondedTokens',
    'EffectiveBondedTokens',
    'OverflowBondedTokens',
    'EffectivePowerBps',
    'IsOverCap',
    'RewardMultiplierBps',
    'LastCommissionChangeTime',
    'LastCommissionRateBps',
    'ConcentrationSnapshot:',
    'Height',
    'BondedRatio',
    'ActiveValidators',
    'Top10Bps',
    'Top20Bps',
    'Top33Bps',
    'NakamotoCoefficientEstimate',
    'All decimal values should use integer basis points or SDK decimal types consistently. Avoid floating point.',
    'The state gate is `BuildAetraStakingPolicyStateSpecReport` in `app/params/aetra_staking_policy_spec.go`',
    'floating point accounting must fail validation',
    '22.3 Parameter Rules',
    'Parameter validation:',
    'ValidatorPowerCapBps:',
    'min: 100      # 1%',
    'max: 500      # 5%',
    'recommended: 200-300',
    'OverflowRewardMultiplierBps:',
    'max: 10000',
    'recommended: 0-3000 for overflow zone',
    'CommissionFloorBps:',
    'max: 1000',
    'recommended: 300-500',
    'CommissionMaxBps:',
    'min: CommissionFloorBps',
    'max: 3000',
    'recommended: 1500-2000',
    'CommissionMaxDailyChangeBps:',
    'min: 1',
    'max: 500',
    'recommended: 50-100',
    'Governance must not be able to set:',
    'cap below 1%',
    'max commission below floor',
    'overflow multiplier above normal reward multiplier',
    'invalid top-N targets',
    'zero active validator target',
    'negative or overflowing math values',
    '0 < Top10TargetBps <= Top20TargetBps <= Top33TargetBps <= 10000',
    'The parameter gate is `BuildAetraStakingPolicyParameterReport` in `app/params/aetra_staking_policy_spec.go`',
    '`DefaultAetraStakingPolicyParameterRuleSet` must encode min, max, and recommended ranges for all bounded bps parameters',
    'negative math inputs must fail validation',
    '22.4 Effective Power Calculation',
    'The implementation must define whether cap affects:',
    'only reward calculation',
    'actual CometBFT voting power',
    'both',
    'Stage 1:',
    'cap affects rewards and delegation warnings',
    'low consensus risk',
    'Stage 2:',
    'cap affects effective staking power used for validator updates',
    'requires deeper integration and heavy tests',
    'validator updates sent to CometBFT use capped power',
    'total voting power remains consistent',
    'no validator can exceed cap',
    'delegation and unbonding shares remain correct',
    'slashing can still slash the underlying raw stake',
    'evidence handling remains correct',
    'Stage 1 must fail if it touches actual CometBFT voting power',
    'Stage 2 must require validator updates sent to CometBFT to use capped power',
    'Stage 2 must require slashing to slash underlying raw stake',
    'The effective power gate is `BuildAetraStakingPolicyEffectivePowerReport` in `app/params/aetra_staking_policy_spec.go`'
  )) {
  Assert-Contains -Text $docText -Pattern ([regex]::Escape($term)) -Message "aetra staking policy spec doc missing: $term"
}

foreach ($term in @(
    'AetraStakingPolicyModuleName',
    'AetraStakingPolicySpecEvidence',
    'AetraStakingPolicySpecReport',
    'DefaultAetraStakingPolicySpecEvidence',
    'ValidateAetraStakingPolicySpec',
    'BuildAetraStakingPolicySpecReport',
    'AetraStakingPolicyPurposeEffectivePowerOverflowCommissionAntiConcentration',
    'AetraStakingPolicyCentralAntiCentralizationModule',
    'AetraStakingPolicyResponsibilityRawStake',
    'AetraStakingPolicyResponsibilityEffectiveStake',
    'AetraStakingPolicyResponsibilityOverflowStake',
    'AetraStakingPolicyResponsibilityEffectiveVotingPowerCap',
    'AetraStakingPolicyResponsibilityOverflowRewardMultiplier',
    'AetraStakingPolicyResponsibilityDelegationConcentrationWarning',
    'AetraStakingPolicyResponsibilityCommissionFloor',
    'AetraStakingPolicyResponsibilityMaxCommission',
    'AetraStakingPolicyResponsibilityMaxCommissionChangeRate',
    'AetraStakingPolicyResponsibilityTopNConcentrationMetrics',
    'AetraStakingPolicyResponsibilityGovernanceParamValidation',
    'AetraStakingPolicyResponsibilityPolicyChangeEvents',
    'AetraStakingPolicyResponsibilityDeterministicExportImport',
    'AetraStakingPolicyStateSpecEvidence',
    'AetraStakingPolicyStateSpecReport',
    'DefaultAetraStakingPolicyStateSpecEvidence',
    'ValidateAetraStakingPolicyStateSpec',
    'BuildAetraStakingPolicyStateSpecReport',
    'AetraStakingPolicyStateParams',
    'AetraStakingPolicyStateValidatorPolicy',
    'AetraStakingPolicyStateConcentrationSnapshot',
    'AetraStakingPolicyStateParamMaxValidatorsSoftTarget',
    'AetraStakingPolicyStateParamValidatorPowerCapBps',
    'AetraStakingPolicyStateParamValidatorPowerCapSchedule',
    'AetraStakingPolicyStateParamOverflowRewardMultiplierBps',
    'AetraStakingPolicyStateParamCommissionFloorBps',
    'AetraStakingPolicyStateParamCommissionMaxBps',
    'AetraStakingPolicyStateParamCommissionMaxDailyChangeBps',
    'AetraStakingPolicyStateParamTop10TargetBps',
    'AetraStakingPolicyStateParamTop20TargetBps',
    'AetraStakingPolicyStateParamTop33TargetBps',
    'AetraStakingPolicyStateParamMinSelfBond',
    'AetraStakingPolicyStateParamMinValidatorBond',
    'AetraStakingPolicyStateParamWarningThresholdBps',
    'AetraStakingPolicyStateValidatorOperatorAddress',
    'AetraStakingPolicyStateValidatorRawBondedTokens',
    'AetraStakingPolicyStateValidatorEffectiveBondedTokens',
    'AetraStakingPolicyStateValidatorOverflowBondedTokens',
    'AetraStakingPolicyStateValidatorEffectivePowerBps',
    'AetraStakingPolicyStateValidatorIsOverCap',
    'AetraStakingPolicyStateValidatorRewardMultiplierBps',
    'AetraStakingPolicyStateValidatorLastCommissionChangeTime',
    'AetraStakingPolicyStateValidatorLastCommissionRateBps',
    'AetraStakingPolicyStateSnapshotHeight',
    'AetraStakingPolicyStateSnapshotBondedRatio',
    'AetraStakingPolicyStateSnapshotActiveValidators',
    'AetraStakingPolicyStateSnapshotTop10Bps',
    'AetraStakingPolicyStateSnapshotTop20Bps',
    'AetraStakingPolicyStateSnapshotTop33Bps',
    'AetraStakingPolicyStateSnapshotNakamotoCoefficientEstimate',
    'AetraStakingPolicyStateIntegerBpsOrSDKDecimal',
    'AetraStakingPolicyStateNoFloatingPoint',
    'AetraStakingPolicyBpsRule',
    'AetraStakingPolicyParameterRuleSet',
    'AetraStakingPolicyParameterValues',
    'AetraStakingPolicyParameterReport',
    'DefaultAetraStakingPolicyParameterRuleSet',
    'DefaultAetraStakingPolicyParameterValues',
    'ValidateAetraStakingPolicyParameterValues',
    'BuildAetraStakingPolicyParameterReport',
    'AetraStakingPolicyParamValidatorPowerCapBps',
    'AetraStakingPolicyParamOverflowRewardMultiplierBps',
    'AetraStakingPolicyParamCommissionFloorBps',
    'AetraStakingPolicyParamCommissionMaxBps',
    'AetraStakingPolicyParamCommissionMaxDailyChangeBps',
    'AetraStakingPolicyParamTop10TargetBps',
    'AetraStakingPolicyParamTop20TargetBps',
    'AetraStakingPolicyParamTop33TargetBps',
    'AetraStakingPolicyParamMaxValidatorsSoftTarget',
    'AetraStakingPolicyParamRejectNegativeOrOverflowMath',
    'AetraStakingPolicyEffectivePowerStage1',
    'AetraStakingPolicyEffectivePowerStage2',
    'AetraStakingPolicyEffectivePowerEvidence',
    'AetraStakingPolicyEffectivePowerReport',
    'DefaultAetraStakingPolicyEffectivePowerStage1Evidence',
    'DefaultAetraStakingPolicyEffectivePowerStage2Evidence',
    'ValidateAetraStakingPolicyEffectivePowerEvidence',
    'BuildAetraStakingPolicyEffectivePowerReport',
    'AetraStakingPolicyEffectivePowerDefinesCapScope',
    'AetraStakingPolicyEffectivePowerRewards',
    'AetraStakingPolicyEffectivePowerDelegationWarnings',
    'AetraStakingPolicyEffectivePowerCometBFTVotingPower',
    'AetraStakingPolicyEffectivePowerStage1LowConsensusRisk',
    'AetraStakingPolicyEffectivePowerStage2DeepIntegrationTests',
    'AetraStakingPolicyEffectivePowerValidatorUpdatesCapped',
    'AetraStakingPolicyEffectivePowerTotalVotingConsistent',
    'AetraStakingPolicyEffectivePowerNoValidatorExceedsCap',
    'AetraStakingPolicyEffectivePowerSharesCorrect',
    'AetraStakingPolicyEffectivePowerSlashingRawStake',
    'AetraStakingPolicyEffectivePowerEvidenceHandlingCorrect'
  )) {
  Assert-Contains -Text $policyText -Pattern ([regex]::Escape($term)) -Message "aetra staking policy spec policy missing: $term"
}

foreach ($term in @(
    'TestDefaultAetraStakingPolicySpecCoversResponsibilities',
    'TestAetraStakingPolicySpecRejectsMissingStakeAndPowerResponsibilities',
    'TestAetraStakingPolicySpecRejectsMissingCommissionConcentrationAndSafetyResponsibilities',
    'TestAetraStakingPolicySpecRejectsMissingPurposeAndCentralModuleRole',
    'TestAetraStakingPolicySpecRejectsWrongModuleIdentity',
    'TestDefaultAetraStakingPolicyStateSpecCoversSuggestedState',
    'TestAetraStakingPolicyStateSpecRejectsMissingParamsFields',
    'TestAetraStakingPolicyStateSpecRejectsMissingValidatorPolicyAndSnapshotFields',
    'TestAetraStakingPolicyStateSpecRejectsUnsafeDecimalAccounting',
    'TestAetraStakingPolicyStateSpecRejectsDuplicateUnexpectedAndWrongModule',
    'TestDefaultAetraStakingPolicyParameterRulesMatchSection223',
    'TestDefaultAetraStakingPolicyParameterValuesPassValidation',
    'TestAetraStakingPolicyParameterRulesRejectUnsafeGovernanceValues',
    'TestAetraStakingPolicyParameterRulesRejectInvalidTopNAndZeroValidatorTarget',
    'TestAetraStakingPolicyParameterRulesRejectNegativeMathValues',
    'TestDefaultAetraStakingPolicyEffectivePowerStage1IsLowConsensusRisk',
    'TestAetraStakingPolicyEffectivePowerStage1RejectsCometBFTPowerMutation',
    'TestDefaultAetraStakingPolicyEffectivePowerStage2RequiresConsensusIntegrationGates',
    'TestAetraStakingPolicyEffectivePowerStage2RejectsMissingValidatorUpdateAndStakeSafety',
    'TestAetraStakingPolicyEffectivePowerRejectsMissingScopeStageAndModule'
  )) {
  Assert-Contains -Text $testText -Pattern ([regex]::Escape($term)) -Message "aetra staking policy spec tests missing: $term"
}

Write-Host "aetra staking policy spec doc test passed"
