param(
  [string]$Doc = "docs\architecture\aetra-staking-policy-spec.md",
  [string]$Policy = "app\params\aetra_staking_policy_spec.go",
  [string]$Tests = "app\params\aetra_staking_policy_spec_test.go"
)

$ErrorActionPreference = "Stop"

$RepoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\.."))

function Resolve-RepoPath {
  param([string]$Path)
  if ([System.IO.Path]::IsPathRooted($Path)) { return $Path }
  return Join-Path $RepoRoot $Path
}

function Assert-Contains {
  param([string]$Text, [string]$Pattern, [string]$Message)
  if ($Text -notmatch $Pattern) { throw $Message }
}

$docText = Get-Content -Raw -LiteralPath (Resolve-RepoPath $Doc)
$policyText = Get-Content -Raw -LiteralPath (Resolve-RepoPath $Policy)
$testText = Get-Content -Raw -LiteralPath (Resolve-RepoPath $Tests)

foreach ($term in @(
    'x/aetra-staking-policy Module Specification',
    'Purpose: control effective voting power, delegation overflow, commission policy, and anti-concentration incentives.',
    'This module is the central anti-centralization module of Aetra.',
    'calculate raw validator stake',
    'calculate effective validator stake',
    'calculate overflow stake',
    'enforce or expose effective voting power cap',
    'calculate reward multiplier for overflow stake',
    'expose delegation concentration warnings',
    'enforce commission floor',
    'enforce max commission',
    'enforce max commission change rate',
    'expose top-N concentration metrics',
    'validate governance param changes',
    'emit events for cap/overflow/commission policy changes',
    'remain deterministic and export/import safe',
    'staking policy = stake math + cap enforcement/exposure + overflow accounting + commission policy + concentration metrics + governance params + events + export/import safety + tests + docs',
    'The implementation gate is `app/params/aetra_staking_policy_spec.go`',
    '`AetraStakingPolicyModuleName` must be `x/aetra-staking-policy`',
    'wrong or missing module identity is rejected',
    '22.2 State',
    'Params:',
    'MaxValidatorsSoftTarget',
    'ValidatorPowerCapBps',
    'ValidatorPowerCapSchedule',
    'OverflowRewardMultiplierBps',
    'CommissionFloorBps',
    'CommissionMaxBps',
    'CommissionMaxDailyChangeBps',
    'Top10TargetBps',
    'Top20TargetBps',
    'Top33TargetBps',
    'MinSelfBond',
    'MinValidatorBond',
    'WarningThresholdBps',
    'ValidatorPolicy:',
    'OperatorAddress',
    'RawBondedTokens',
    'EffectiveBondedTokens',
    'OverflowBondedTokens',
    'EffectivePowerBps',
    'IsOverCap',
    'RewardMultiplierBps',
    'LastCommissionChangeTime',
    'LastCommissionRateBps',
    'ConcentrationSnapshot:',
    'Height',
    'BondedRatio',
    'ActiveValidators',
    'Top10Bps',
    'Top20Bps',
    'Top33Bps',
    'NakamotoCoefficientEstimate',
    'All decimal values should use integer basis points or SDK decimal types consistently. Avoid floating point.',
    'The state gate is `BuildAetraStakingPolicyStateSpecReport` in `app/params/aetra_staking_policy_spec.go`',
    'floating point accounting must fail validation',
    '22.3 Parameter Rules',
    'Parameter validation:',
    'ValidatorPowerCapBps:',
    'min: 100      # 1%',
    'max: 500      # 5%',
    'recommended: 200-300',
    'OverflowRewardMultiplierBps:',
    'max: 10000',
    'recommended: 0-3000 for overflow zone',
    'CommissionFloorBps:',
    'max: 1000',
    'recommended: 300-500',
    'CommissionMaxBps:',
    'min: CommissionFloorBps',
    'max: 3000',
    'recommended: 1500-2000',
    'CommissionMaxDailyChangeBps:',
    'min: 1',
    'max: 500',
    'recommended: 50-100',
    'Governance must not be able to set:',
    'cap below 1%',
    'max commission below floor',
    'overflow multiplier above normal reward multiplier',
    'invalid top-N targets',
    'zero active validator target',
    'negative or overflowing math values',
    '0 < Top10TargetBps <= Top20TargetBps <= Top33TargetBps <= 10000',
    'The parameter gate is `BuildAetraStakingPolicyParameterReport` in `app/params/aetra_staking_policy_spec.go`',
    '`DefaultAetraStakingPolicyParameterRuleSet` must encode min, max, and recommended ranges for all bounded bps parameters',
    'negative math inputs must fail validation',
    '22.4 Effective Power Calculation',
    'The implementation must define whether cap affects:',
    'only reward calculation',
    'actual CometBFT voting power',
    'both',
    'Stage 1:',
    'cap affects rewards and delegation warnings',
    'low consensus risk',
    'Stage 2:',
    'cap affects effective staking power used for validator updates',
    'requires deeper integration and heavy tests',
    'validator updates sent to CometBFT use capped power',
    'total voting power remains consistent',
    'no validator can exceed cap',
    'delegation and unbonding shares remain correct',
    'slashing can still slash the underlying raw stake',
    'evidence handling remains correct',
    'Stage 1 must fail if it touches actual CometBFT voting power',
    'Stage 2 must require validator updates sent to CometBFT to use capped power',
    'Stage 2 must require slashing to slash underlying raw stake',
    'The effective power gate is `BuildAetraStakingPolicyEffectivePowerReport` in `app/params/aetra_staking_policy_spec.go`',
    '22.5 Messages',
    'Required governance-only or authority-only messages:',
    'MsgUpdateStakingPolicyParams',
    'MsgUpdateValidatorPowerCapSchedule',
    'MsgSetCommissionPolicy',
    'Optional validator messages:',
    'MsgRegisterValidatorIdentity',
    'MsgUpdateValidatorIdentity',
    'MsgAcknowledgeOverCapWarning',
    'validate authority',
    'validate signer',
    'reject malformed addresses',
    'reject invalid params',
    'emit events',
    'be covered by tests',
    'The message gate is `BuildAetraStakingPolicyMessageSpecReport` in `app/params/aetra_staking_policy_spec.go`',
    '22.6 Queries',
    'Required queries:',
    'Query/Params',
    'Query/ValidatorPolicy',
    'Query/ValidatorEffectivePower',
    'Query/ValidatorOverflow',
    'Query/TopNConcentration',
    'Query/DelegationWarning',
    'Query/CommissionPolicy',
    'Query/ConcentrationSnapshot',
    'Query/NakamotoCoefficient',
    'Query responses must be stable and indexer-friendly',
    'The query gate is `BuildAetraStakingPolicyQuerySpecReport` in `app/params/aetra_staking_policy_spec.go`',
    '22.7 Events',
    'Required events:',
    'aetra.staking_policy.params_updated',
    'aetra.staking_policy.validator_over_cap',
    'aetra.staking_policy.validator_back_under_cap',
    'aetra.staking_policy.commission_rejected',
    'aetra.staking_policy.concentration_snapshot',
    'aetra.staking_policy.reward_multiplier_changed',
    'The event gate is `BuildAetraStakingPolicyEventSpecReport` in `app/params/aetra_staking_policy_spec.go`',
    '22.8 Invariants',
    'Required invariants:',
    'effective power never exceeds configured cap',
    'overflow stake is never negative',
    'raw stake = effective stake + overflow stake for capped calculation',
    'commission floor <= commission <= commission max',
    'commission change <= max daily change',
    'top-N calculations do not exceed 100%',
    'state export/import preserves policy state',
    'The invariant gate is `BuildAetraStakingPolicyInvariantSpecReport` in `app/params/aetra_staking_policy_spec.go`',
    'top-N calculations never exceed `10000` bps',
    'invariants must be covered by tests',
    '22.9 Tests',
    'Required tests:',
    'cap math for 100 validators',
    'cap math for 150 validators',
    'cap math for 250 validators',
    'cap math for 300 validators',
    'validator crossing cap upward',
    'validator crossing cap downward',
    'delegation to over-cap validator',
    'redelegation from over-cap validator',
    'unbonding from over-cap validator',
    'slashing over-cap validator',
    'commission below floor rejected',
    'commission above max rejected',
    'commission daily jump rejected',
    'governance param update accepted within bounds',
    'governance param update rejected outside bounds',
    'export/import with over-cap validators',
    'deterministic concentration snapshot',
    'The test gate is `BuildAetraStakingPolicyTestSpecReport` in `app/params/aetra_staking_policy_spec.go`'
  )) {
  Assert-Contains -Text $docText -Pattern ([regex]::Escape($term)) -Message "aetra staking policy spec doc missing: $term"
}

foreach ($term in @(
    'AetraStakingPolicyModuleName',
    'AetraStakingPolicySpecEvidence',
    'AetraStakingPolicySpecReport',
    'DefaultAetraStakingPolicySpecEvidence',
    'ValidateAetraStakingPolicySpec',
    'BuildAetraStakingPolicySpecReport',
    'AetraStakingPolicyPurposeEffectivePowerOverflowCommissionAntiConcentration',
    'AetraStakingPolicyCentralAntiCentralizationModule',
    'AetraStakingPolicyResponsibilityRawStake',
    'AetraStakingPolicyResponsibilityEffectiveStake',
    'AetraStakingPolicyResponsibilityOverflowStake',
    'AetraStakingPolicyResponsibilityEffectiveVotingPowerCap',
    'AetraStakingPolicyResponsibilityOverflowRewardMultiplier',
    'AetraStakingPolicyResponsibilityDelegationConcentrationWarning',
    'AetraStakingPolicyResponsibilityCommissionFloor',
    'AetraStakingPolicyResponsibilityMaxCommission',
    'AetraStakingPolicyResponsibilityMaxCommissionChangeRate',
    'AetraStakingPolicyResponsibilityTopNConcentrationMetrics',
    'AetraStakingPolicyResponsibilityGovernanceParamValidation',
    'AetraStakingPolicyResponsibilityPolicyChangeEvents',
    'AetraStakingPolicyResponsibilityDeterministicExportImport',
    'AetraStakingPolicyStateSpecEvidence',
    'AetraStakingPolicyStateSpecReport',
    'DefaultAetraStakingPolicyStateSpecEvidence',
    'ValidateAetraStakingPolicyStateSpec',
    'BuildAetraStakingPolicyStateSpecReport',
    'AetraStakingPolicyStateParams',
    'AetraStakingPolicyStateValidatorPolicy',
    'AetraStakingPolicyStateConcentrationSnapshot',
    'AetraStakingPolicyStateParamMaxValidatorsSoftTarget',
    'AetraStakingPolicyStateParamValidatorPowerCapBps',
    'AetraStakingPolicyStateParamValidatorPowerCapSchedule',
    'AetraStakingPolicyStateParamOverflowRewardMultiplierBps',
    'AetraStakingPolicyStateParamCommissionFloorBps',
    'AetraStakingPolicyStateParamCommissionMaxBps',
    'AetraStakingPolicyStateParamCommissionMaxDailyChangeBps',
    'AetraStakingPolicyStateParamTop10TargetBps',
    'AetraStakingPolicyStateParamTop20TargetBps',
    'AetraStakingPolicyStateParamTop33TargetBps',
    'AetraStakingPolicyStateParamMinSelfBond',
    'AetraStakingPolicyStateParamMinValidatorBond',
    'AetraStakingPolicyStateParamWarningThresholdBps',
    'AetraStakingPolicyStateValidatorOperatorAddress',
    'AetraStakingPolicyStateValidatorRawBondedTokens',
    'AetraStakingPolicyStateValidatorEffectiveBondedTokens',
    'AetraStakingPolicyStateValidatorOverflowBondedTokens',
    'AetraStakingPolicyStateValidatorEffectivePowerBps',
    'AetraStakingPolicyStateValidatorIsOverCap',
    'AetraStakingPolicyStateValidatorRewardMultiplierBps',
    'AetraStakingPolicyStateValidatorLastCommissionChangeTime',
    'AetraStakingPolicyStateValidatorLastCommissionRateBps',
    'AetraStakingPolicyStateSnapshotHeight',
    'AetraStakingPolicyStateSnapshotBondedRatio',
    'AetraStakingPolicyStateSnapshotActiveValidators',
    'AetraStakingPolicyStateSnapshotTop10Bps',
    'AetraStakingPolicyStateSnapshotTop20Bps',
    'AetraStakingPolicyStateSnapshotTop33Bps',
    'AetraStakingPolicyStateSnapshotNakamotoCoefficientEstimate',
    'AetraStakingPolicyStateIntegerBpsOrSDKDecimal',
    'AetraStakingPolicyStateNoFloatingPoint',
    'AetraStakingPolicyBpsRule',
    'AetraStakingPolicyParameterRuleSet',
    'AetraStakingPolicyParameterValues',
    'AetraStakingPolicyParameterReport',
    'DefaultAetraStakingPolicyParameterRuleSet',
    'DefaultAetraStakingPolicyParameterValues',
    'ValidateAetraStakingPolicyParameterValues',
    'BuildAetraStakingPolicyParameterReport',
    'AetraStakingPolicyParamValidatorPowerCapBps',
    'AetraStakingPolicyParamOverflowRewardMultiplierBps',
    'AetraStakingPolicyParamCommissionFloorBps',
    'AetraStakingPolicyParamCommissionMaxBps',
    'AetraStakingPolicyParamCommissionMaxDailyChangeBps',
    'AetraStakingPolicyParamTop10TargetBps',
    'AetraStakingPolicyParamTop20TargetBps',
    'AetraStakingPolicyParamTop33TargetBps',
    'AetraStakingPolicyParamMaxValidatorsSoftTarget',
    'AetraStakingPolicyParamRejectNegativeOrOverflowMath',
    'AetraStakingPolicyEffectivePowerStage1',
    'AetraStakingPolicyEffectivePowerStage2',
    'AetraStakingPolicyEffectivePowerEvidence',
    'AetraStakingPolicyEffectivePowerReport',
    'DefaultAetraStakingPolicyEffectivePowerStage1Evidence',
    'DefaultAetraStakingPolicyEffectivePowerStage2Evidence',
    'ValidateAetraStakingPolicyEffectivePowerEvidence',
    'BuildAetraStakingPolicyEffectivePowerReport',
    'AetraStakingPolicyEffectivePowerDefinesCapScope',
    'AetraStakingPolicyEffectivePowerRewards',
    'AetraStakingPolicyEffectivePowerDelegationWarnings',
    'AetraStakingPolicyEffectivePowerCometBFTVotingPower',
    'AetraStakingPolicyEffectivePowerStage1LowConsensusRisk',
    'AetraStakingPolicyEffectivePowerStage2DeepIntegrationTests',
    'AetraStakingPolicyEffectivePowerValidatorUpdatesCapped',
    'AetraStakingPolicyEffectivePowerTotalVotingConsistent',
    'AetraStakingPolicyEffectivePowerNoValidatorExceedsCap',
    'AetraStakingPolicyEffectivePowerSharesCorrect',
    'AetraStakingPolicyEffectivePowerSlashingRawStake',
    'AetraStakingPolicyEffectivePowerEvidenceHandlingCorrect',
    'AetraStakingPolicyMessageSpecEvidence',
    'AetraStakingPolicyMessageSpecReport',
    'DefaultAetraStakingPolicyMessageSpecEvidence',
    'ValidateAetraStakingPolicyMessageSpec',
    'BuildAetraStakingPolicyMessageSpecReport',
    'AetraStakingPolicyMessageMsgUpdateStakingPolicyParams',
    'AetraStakingPolicyMessageMsgUpdateValidatorPowerCapSchedule',
    'AetraStakingPolicyMessageMsgSetCommissionPolicy',
    'AetraStakingPolicyMessageMsgRegisterValidatorIdentity',
    'AetraStakingPolicyMessageMsgUpdateValidatorIdentity',
    'AetraStakingPolicyMessageMsgAcknowledgeOverCapWarning',
    'AetraStakingPolicyMessageValidateAuthority',
    'AetraStakingPolicyMessageValidateSigner',
    'AetraStakingPolicyMessageRejectMalformedAddresses',
    'AetraStakingPolicyMessageRejectInvalidParams',
    'AetraStakingPolicyMessageEmitEvents',
    'AetraStakingPolicyMessageCoveredByTests',
    'AetraStakingPolicyQuerySpecEvidence',
    'AetraStakingPolicyQuerySpecReport',
    'DefaultAetraStakingPolicyQuerySpecEvidence',
    'ValidateAetraStakingPolicyQuerySpec',
    'BuildAetraStakingPolicyQuerySpecReport',
    'AetraStakingPolicyQueryParams',
    'AetraStakingPolicyQueryValidatorPolicy',
    'AetraStakingPolicyQueryValidatorEffectivePower',
    'AetraStakingPolicyQueryValidatorOverflow',
    'AetraStakingPolicyQueryTopNConcentration',
    'AetraStakingPolicyQueryDelegationWarning',
    'AetraStakingPolicyQueryCommissionPolicy',
    'AetraStakingPolicyQueryConcentrationSnapshot',
    'AetraStakingPolicyQueryNakamotoCoefficient',
    'AetraStakingPolicyQueryStableResponses',
    'AetraStakingPolicyQueryIndexerFriendlyResponses',
    'AetraStakingPolicyEventSpecEvidence',
    'AetraStakingPolicyEventSpecReport',
    'DefaultAetraStakingPolicyEventSpecEvidence',
    'ValidateAetraStakingPolicyEventSpec',
    'BuildAetraStakingPolicyEventSpecReport',
    'AetraStakingPolicyEventParamsUpdated',
    'AetraStakingPolicyEventValidatorOverCap',
    'AetraStakingPolicyEventValidatorBackUnderCap',
    'AetraStakingPolicyEventCommissionRejected',
    'AetraStakingPolicyEventConcentrationSnapshot',
    'AetraStakingPolicyEventRewardMultiplierChanged',
    'AetraStakingPolicyEventStableNames',
    'AetraStakingPolicyEventIndexerFriendlyAttrs',
    'AetraStakingPolicyInvariantSpecEvidence',
    'AetraStakingPolicyInvariantSpecReport',
    'DefaultAetraStakingPolicyInvariantSpecEvidence',
    'ValidateAetraStakingPolicyInvariantSpec',
    'BuildAetraStakingPolicyInvariantSpecReport',
    'AetraStakingPolicyInvariantEffectivePowerCap',
    'AetraStakingPolicyInvariantOverflowNonNegative',
    'AetraStakingPolicyInvariantRawStakeConservation',
    'AetraStakingPolicyInvariantCommissionBounds',
    'AetraStakingPolicyInvariantCommissionDailyChange',
    'AetraStakingPolicyInvariantTopNMaxHundredPercent',
    'AetraStakingPolicyInvariantExportImportPreserves',
    'AetraStakingPolicyInvariantCoveredByTests',
    'AetraStakingPolicyTestSpecEvidence',
    'AetraStakingPolicyTestSpecReport',
    'DefaultAetraStakingPolicyTestSpecEvidence',
    'ValidateAetraStakingPolicyTestSpec',
    'BuildAetraStakingPolicyTestSpecReport',
    'AetraStakingPolicyTestCapMath100Validators',
    'AetraStakingPolicyTestCapMath150Validators',
    'AetraStakingPolicyTestCapMath250Validators',
    'AetraStakingPolicyTestCapMath300Validators',
    'AetraStakingPolicyTestValidatorCrossingCapUpward',
    'AetraStakingPolicyTestValidatorCrossingCapDownward',
    'AetraStakingPolicyTestDelegationToOverCapValidator',
    'AetraStakingPolicyTestRedelegationFromOverCapValidator',
    'AetraStakingPolicyTestUnbondingFromOverCapValidator',
    'AetraStakingPolicyTestSlashingOverCapValidator',
    'AetraStakingPolicyTestCommissionBelowFloorRejected',
    'AetraStakingPolicyTestCommissionAboveMaxRejected',
    'AetraStakingPolicyTestCommissionDailyJumpRejected',
    'AetraStakingPolicyTestGovernanceParamUpdateAccepted',
    'AetraStakingPolicyTestGovernanceParamUpdateRejected',
    'AetraStakingPolicyTestExportImportOverCapValidators',
    'AetraStakingPolicyTestDeterministicConcentrationSnapshot'
  )) {
  Assert-Contains -Text $policyText -Pattern ([regex]::Escape($term)) -Message "aetra staking policy spec policy missing: $term"
}

foreach ($term in @(
    'TestDefaultAetraStakingPolicySpecCoversResponsibilities',
    'TestAetraStakingPolicySpecRejectsMissingStakeAndPowerResponsibilities',
    'TestAetraStakingPolicySpecRejectsMissingCommissionConcentrationAndSafetyResponsibilities',
    'TestAetraStakingPolicySpecRejectsMissingPurposeAndCentralModuleRole',
    'TestAetraStakingPolicySpecRejectsWrongModuleIdentity',
    'TestDefaultAetraStakingPolicyStateSpecCoversSuggestedState',
    'TestAetraStakingPolicyStateSpecRejectsMissingParamsFields',
    'TestAetraStakingPolicyStateSpecRejectsMissingValidatorPolicyAndSnapshotFields',
    'TestAetraStakingPolicyStateSpecRejectsUnsafeDecimalAccounting',
    'TestAetraStakingPolicyStateSpecRejectsDuplicateUnexpectedAndWrongModule',
    'TestDefaultAetraStakingPolicyParameterRulesMatchSection223',
    'TestDefaultAetraStakingPolicyParameterValuesPassValidation',
    'TestAetraStakingPolicyParameterRulesRejectUnsafeGovernanceValues',
    'TestAetraStakingPolicyParameterRulesRejectInvalidTopNAndZeroValidatorTarget',
    'TestAetraStakingPolicyParameterRulesRejectNegativeMathValues',
    'TestDefaultAetraStakingPolicyEffectivePowerStage1IsLowConsensusRisk',
    'TestAetraStakingPolicyEffectivePowerStage1RejectsCometBFTPowerMutation',
    'TestDefaultAetraStakingPolicyEffectivePowerStage2RequiresConsensusIntegrationGates',
    'TestAetraStakingPolicyEffectivePowerStage2RejectsMissingValidatorUpdateAndStakeSafety',
    'TestAetraStakingPolicyEffectivePowerRejectsMissingScopeStageAndModule',
    'TestDefaultAetraStakingPolicyMessageSpecCoversRequiredAndOptionalMessages',
    'TestAetraStakingPolicyMessageSpecRejectsMissingMessagesAndChecks',
    'TestAetraStakingPolicyMessageSpecRejectsDuplicateUnexpectedAndWrongModule',
    'TestDefaultAetraStakingPolicyQuerySpecCoversRequiredQueries',
    'TestAetraStakingPolicyQuerySpecRejectsMissingUnstableAndNonIndexerFriendlyQueries',
    'TestAetraStakingPolicyQuerySpecRejectsDuplicateUnexpectedAndWrongModule',
    'TestDefaultAetraStakingPolicyEventSpecCoversRequiredEvents',
    'TestAetraStakingPolicyEventSpecRejectsMissingDuplicateUnexpectedAndUnstableEvents',
    'TestDefaultAetraStakingPolicyInvariantSpecCoversRequiredInvariants',
    'TestAetraStakingPolicyInvariantSpecRejectsMissingSafetyInvariants',
    'TestAetraStakingPolicyInvariantSpecRejectsWrongModuleIdentity',
    'TestDefaultAetraStakingPolicyTestSpecCoversRequiredTests',
    'TestAetraStakingPolicyTestSpecRejectsMissingDuplicateUnexpectedAndWrongModule'
  )) {
  Assert-Contains -Text $testText -Pattern ([regex]::Escape($term)) -Message "aetra staking policy spec tests missing: $term"
}

Write-Host "aetra staking policy spec doc test passed"
