param(
  [string]$Doc = "docs\architecture\implementation-phases.md",
  [string]$Policy = "app\params\implementation_phases.go",
  [string]$Tests = "app\params\implementation_phases_test.go"
)

$ErrorActionPreference = "Stop"

$RepoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\.."))

function Resolve-RepoPath {
  param([string]$Path)
  if ([System.IO.Path]::IsPathRooted($Path)) { return $Path }
  return Join-Path $RepoRoot $Path
}

function Assert-Contains {
  param([string]$Text, [string]$Pattern, [string]$Message)
  if ($Text -notmatch $Pattern) { throw $Message }
}

$docText = Get-Content -Raw -LiteralPath (Resolve-RepoPath $Doc)
$policyText = Get-Content -Raw -LiteralPath (Resolve-RepoPath $Policy)
$testText = Get-Content -Raw -LiteralPath (Resolve-RepoPath $Tests)

foreach ($term in @(
    'Implementation Phases',
    'Phase 0 - Baseline Audit',
    'inspect current Cosmos SDK and CometBFT versions',
    'document current app module graph',
    'identify existing modules overlapping with `aetra-staking-policy`, `aetra-validator-score`, and `aetra-economics`',
    'decide which modules are renamed, reused, or wrapped',
    'verify current `naet` staking denom',
    'verify fee collector, burn, treasury, emissions, mint authority wiring',
    'verify current localnet scripts and test coverage',
    'module inventory',
    'gap analysis',
    'risk list',
    'updated implementation checklist',
    'current full unit test run',
    'current integration test run',
    'current localnet smoke test',
    'current export/import test',
    'Phase 1 - Staking Policy and Validator Cap',
    'implement effective voting power cap',
    'implement overflow stake accounting',
    'implement commission floor/max/max-change policy',
    'add concentration metrics',
    'add queries for validator raw/effective/overflow stake',
    'add governance params with validation',
    'wire module into app lifecycle',
    'cap math unit tests',
    'validator set transition tests',
    'concentration query tests',
    'commission bounds tests',
    'integration tests with staking',
    'export/import tests',
    'invariant tests',
    'no validator can exceed configured effective power cap',
    'excess stake does not increase voting power',
    'params cannot be set outside safe bounds',
    'state remains deterministic after export/import',
    'Phase 2 - Economics and Fee Split',
    'implement dynamic inflation bounds',
    'implement target bonded ratio logic',
    'implement fee split to burn/rewards/treasury',
    'implement reward smoothing',
    'expose APR estimate query',
    'expose burned supply and treasury accounting queries',
    'add governance param controls',
    'inflation curve tests',
    'bonded ratio tests',
    'fee split tests',
    'burn accounting tests',
    'treasury accounting tests',
    'APR query tests',
    'supply invariant tests',
    'inflation remains within configured bounds',
    'fee split sums to 100 percent',
    'burned fees reduce spendable/module-held supply according to chain accounting rules',
    'treasury receives correct amount',
    'rewards are deterministic',
    'Phase 3 - Validator Score and Accountability',
    'implement uptime score',
    'implement slash history',
    'implement governance participation score',
    'implement decentralization score',
    'implement public validator metrics queries',
    'integrate score with reward modifier only for objective inputs',
    'uptime window tests',
    'missed block tests',
    'slash history tests',
    'governance participation tests',
    'score determinism tests',
    'reward modifier tests',
    'score is deterministic',
    'score cannot be manipulated through subjective inputs',
    'score is queryable for explorers and wallets',
    'score does not break consensus safety',
    'Phase 4 - Slashing Hardening',
    'configure double-sign slash fraction and tombstone behavior',
    'configure downtime windows and jail duration',
    'implement progressive downtime if not covered by standard module',
    'add timestamp/proposal violation policy where objective',
    'document evidence lifecycle and unbonding interaction',
    'double-sign evidence tests where feasible',
    'downtime tests',
    'jail/unjail tests',
    'progressive downtime tests',
    'slashing accounting tests',
    'delegator loss tests',
    'tombstone tests',
    'evidence expiry tests',
    'double-sign leads to severe slash and permanent tombstone',
    'downtime penalties are bounded and progressive',
    'no subjective slashing path exists',
    'slashing cannot underflow stake or corrupt shares',
    'Phase 5 - AVM Integration',
    'finalize AVM module wiring',
    'define code upload policy',
    'define contract gas limits',
    'define contract size limits',
    'integrate storage rent or storage pricing',
    'expose contract events for indexers',
    'document contract developer flow',
    'instantiate/execute/query tests',
    'migration tests',
    'gas limit tests',
    'storage limit/rent tests',
    'malicious contract tests',
    'export/import tests with contracts',
    'localnet AVM smoke test',
    'contracts are deterministic',
    'contract gas is bounded',
    'malicious contracts cannot halt chain',
    'contract state survives export/import',
    'Phase 6 - Finality and Performance Profile',
    'configure block time targets',
    'configure block size/gas limits',
    'profile 100 validator localnet',
    'profile 150-200 validator scenario if feasible',
    'estimate 250-300 validator operational requirements',
    'measure finality under load',
    'measure finality under partial validator failure',
    'localnet load profile',
    'mempool pressure test',
    'block time measurement',
    'finality measurement',
    'validator failure scenario',
    'restart scenario',
    'state sync/snapshot scenario',
    'normal finality remains within target',
    'stressed finality remains below 120 seconds in healthy majority scenario',
    'node requirements remain medium-level',
    'no excessive consensus payloads',
    'Phase 7 - Public Testnet Readiness',
    'write validator setup docs',
    'write sentry architecture docs',
    'write monitoring docs',
    'publish genesis parameter explanation',
    'publish economic model explanation',
    'publish slashing risk explanation',
    'publish delegation and nomination pool guide',
    'publish AVM developer guide',
    'prepare public dashboards',
    'prepare incident response process',
    'clean node bootstrap from docs',
    'validator join from docs',
    'snapshot restore from docs',
    'state sync from docs',
    'tx flow smoke tests',
    'governance proposal smoke tests',
    'public RPC/gRPC/REST smoke tests',
    'new validator can join using docs',
    'public endpoints are observable',
    'network can recover from node restarts',
    'core economic and staking flows work end to end'
  )) {
  Assert-Contains -Text $docText -Pattern ([regex]::Escape($term)) -Message "implementation phases doc missing: $term"
}

foreach ($term in @(
    'ImplementationPhaseBaselineAudit',
    'ImplementationPhaseStakingPolicyCap',
    'ImplementationPhaseEconomicsFeeSplit',
    'ImplementationPhaseValidatorScore',
    'ImplementationPhaseSlashingHardening',
    'ImplementationPhaseAVMIntegration',
    'ImplementationPhaseFinalityPerformance',
    'ImplementationPhasePublicTestnetReady',
    'ImplementationPhaseItem',
    'ImplementationPhasePlan',
    'ImplementationPhaseReport',
    'DefaultImplementationPhasePlans',
    'ValidateImplementationPhasePlan',
    'BuildImplementationPhaseReport',
    'PhaseTaskInspectVersions',
    'PhaseTaskDocumentModuleGraph',
    'PhaseTaskIdentifyOverlappingModules',
    'PhaseTaskDecideRenameReuseWrap',
    'PhaseTaskVerifyNaetStakingDenom',
    'PhaseTaskVerifyEconomyWiring',
    'PhaseTaskVerifyLocalnetAndCoverage',
    'PhaseDeliverableModuleInventory',
    'PhaseDeliverableGapAnalysis',
    'PhaseDeliverableRiskList',
    'PhaseDeliverableImplementationChecklist',
    'PhaseTaskImplementEffectivePowerCap',
    'PhaseTaskImplementOverflowAccounting',
    'PhaseTaskImplementCommissionPolicy',
    'PhaseTaskAddConcentrationMetrics',
    'PhaseTaskAddStakeQueries',
    'PhaseTaskAddGovernanceParams',
    'PhaseTaskWireModuleLifecycle',
    'PhaseTaskImplementInflationBounds',
    'PhaseTaskImplementTargetBondedRatio',
    'PhaseTaskImplementFeeSplit',
    'PhaseTaskImplementRewardSmoothing',
    'PhaseTaskExposeAPREstimateQuery',
    'PhaseTaskExposeSupplyTreasuryQueries',
    'PhaseTaskAddEconomicsGovernanceParams',
    'PhaseTaskImplementUptimeScore',
    'PhaseTaskImplementSlashHistory',
    'PhaseTaskImplementGovernanceScore',
    'PhaseTaskImplementDecentralizationScore',
    'PhaseTaskImplementValidatorMetricQueries',
    'PhaseTaskIntegrateObjectiveRewardModifier',
    'PhaseTaskConfigureDoubleSignSlashTombstone',
    'PhaseTaskConfigureDowntimeJail',
    'PhaseTaskImplementProgressiveDowntime',
    'PhaseTaskAddObjectiveTimestampProposalPolicy',
    'PhaseTaskDocumentEvidenceLifecycle',
    'PhaseTaskFinalizeAVMWiring',
    'PhaseTaskDefineCodeUploadPolicy',
    'PhaseTaskDefineContractGasLimits',
    'PhaseTaskDefineContractSizeLimits',
    'PhaseTaskIntegrateStorageRentPricing',
    'PhaseTaskExposeContractIndexerEvents',
    'PhaseTaskDocumentContractDeveloperFlow',
    'PhaseTaskConfigureBlockTimeTargets',
    'PhaseTaskConfigureBlockSizeGasLimits',
    'PhaseTaskProfile100ValidatorLocalnet',
    'PhaseTaskProfile150To200Validators',
    'PhaseTaskEstimate250To300Requirements',
    'PhaseTaskMeasureFinalityUnderLoad',
    'PhaseTaskMeasureFinalityUnderValidatorFailure',
    'PhaseTaskWriteValidatorSetupDocs',
    'PhaseTaskWriteSentryArchitectureDocs',
    'PhaseTaskWriteMonitoringDocs',
    'PhaseTaskPublishGenesisParamExplanation',
    'PhaseTaskPublishEconomicModelExplanation',
    'PhaseTaskPublishSlashingRiskExplanation',
    'PhaseTaskPublishDelegationPoolGuide',
    'PhaseTaskPublishAVMDeveloperGuide',
    'PhaseTaskPreparePublicDashboards',
    'PhaseTaskPrepareIncidentResponseProcess',
    'PhaseTestInflationCurve',
    'PhaseTestBondedRatio',
    'PhaseTestFeeSplit',
    'PhaseTestBurnAccounting',
    'PhaseTestTreasuryAccounting',
    'PhaseTestAPRQuery',
    'PhaseTestSupplyInvariant',
    'PhaseTestEconomicsExportImport',
    'PhaseTestUptimeWindow',
    'PhaseTestMissedBlock',
    'PhaseTestSlashHistory',
    'PhaseTestGovernanceParticipation',
    'PhaseTestScoreDeterminism',
    'PhaseTestRewardModifier',
    'PhaseTestValidatorScoreExportImport',
    'PhaseTestDoubleSignEvidence',
    'PhaseTestDowntime',
    'PhaseTestJailUnjail',
    'PhaseTestProgressiveDowntime',
    'PhaseTestSlashingAccounting',
    'PhaseTestDelegatorLoss',
    'PhaseTestTombstone',
    'PhaseTestEvidenceExpiry',
    'PhaseTestContractTxFlow',
    'PhaseTestContractMigration',
    'PhaseTestContractGasLimit',
    'PhaseTestContractStorageLimitRent',
    'PhaseTestMaliciousContract',
    'PhaseTestContractExportImport',
    'PhaseTestLocalnetAVMSmoke',
    'PhaseTestLocalnetLoadProfile',
    'PhaseTestMempoolPressure',
    'PhaseTestBlockTimeMeasurement',
    'PhaseTestFinalityMeasurement',
    'PhaseTestValidatorFailureScenario',
    'PhaseTestRestartScenario',
    'PhaseTestStateSyncSnapshotScenario',
    'PhaseTestCleanNodeBootstrapDocs',
    'PhaseTestValidatorJoinDocs',
    'PhaseTestSnapshotRestoreDocs',
    'PhaseTestStateSyncDocs',
    'PhaseTestTxFlowSmoke',
    'PhaseTestGovernanceProposalSmoke',
    'PhaseTestPublicEndpointSmoke',
    'PhaseAcceptanceNoValidatorExceedsCap',
    'PhaseAcceptanceExcessNoVotingPower',
    'PhaseAcceptanceParamsSafeBounds',
    'PhaseAcceptanceDeterministicExportImport',
    'PhaseAcceptanceInflationWithinBounds',
    'PhaseAcceptanceFeeSplitSumsToFullAmount',
    'PhaseAcceptanceBurnReducesSupply',
    'PhaseAcceptanceTreasuryReceivesAmount',
    'PhaseAcceptanceRewardsDeterministic',
    'PhaseAcceptanceScoreDeterministic',
    'PhaseAcceptanceScoreObjectiveOnly',
    'PhaseAcceptanceScoreQueryable',
    'PhaseAcceptanceScoreConsensusSafe',
    'PhaseAcceptanceDoubleSignTombstone',
    'PhaseAcceptanceDowntimeBoundedProgressive',
    'PhaseAcceptanceNoSubjectiveSlashing',
    'PhaseAcceptanceSlashingStakeShareSafe',
    'PhaseAcceptanceContractsDeterministic',
    'PhaseAcceptanceContractGasBounded',
    'PhaseAcceptanceMaliciousContractsSafe',
    'PhaseAcceptanceContractStateExportImport',
    'PhaseAcceptanceNormalFinalityWithinTarget',
    'PhaseAcceptanceStressedFinalityUnderLimit',
    'PhaseAcceptanceMediumNodeRequirements',
    'PhaseAcceptanceNoExcessiveConsensusPayloads',
    'PhaseAcceptanceValidatorCanJoinFromDocs',
    'PhaseAcceptancePublicEndpointsObservable',
    'PhaseAcceptanceNetworkRecoversRestarts',
    'PhaseAcceptanceCoreFlowsEndToEnd'
  )) {
  Assert-Contains -Text $policyText -Pattern ([regex]::Escape($term)) -Message "implementation phases policy missing: $term"
}

foreach ($term in @(
    'TestDefaultImplementationPhasePlansCoverPhase0ThroughPhase7',
    'TestImplementationPhaseRejectsMissingEvidence',
    'TestImplementationPhaseRejectsMissingRequiredItem',
    'TestImplementationPhaseEconomicsFeeSplitRequiresAllAcceptanceGates',
    'TestImplementationPhaseValidatorScoreRequiresAllAcceptanceGates',
    'TestImplementationPhaseSlashingHardeningRequiresAllAcceptanceGates',
    'TestImplementationPhaseAVMIntegrationRequiresAllAcceptanceGates',
    'TestImplementationPhaseFinalityPerformanceRequiresAllAcceptanceGates',
    'TestImplementationPhasePublicTestnetReadinessRequiresAllAcceptanceGates',
    'TestImplementationPhaseRejectsUnknownPhaseAndUnexpectedItem'
  )) {
  Assert-Contains -Text $testText -Pattern ([regex]::Escape($term)) -Message "implementation phases tests missing: $term"
}

Write-Host "implementation phases doc test passed"
